spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    username: root
    password: qwe123
    url: jdbc:mariadb://localhost:3306/mangodb


