spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update #실제 운영 DB에는 auto-ddl 기능을 사용하지 않음
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # DB회사마다 SQL이 조금씩 다른데 그걸 자동으로 맞춰줌
    show-sql: true # console 창에 실행되는 SQL을 출력함

  datasource:
    username: root
    password: qwe123
    url: jdbc:mariadb://localhost:3306/mangodb


