apiVersion: v1
kind: Service
metadata:
  name: mango-server
spec:
  clusterIp: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: server-port
  selector:
    app: mango-server
